steps: 
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - "--ciphertext-file=cicd-dev.encrypted"
  - "--plaintext-file=cicd-dev.decrypted"
  - "--location=global"
  - "--keyring=apigee-cicd-credentials"
  - "--key=cicd-dev"
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn -P dev install -Dapigee.username=$$USERNAME -Dapigee.serviceaccount.file=$_SAFILE -Dportal.username=$$PORTAL_USERNAME -Dportal.password=$$PORTAL_PASSWORD -Dcommit="${COMMIT_SHA} via GCP" -Dbranch=${BRANCH_NAME}']
  dir: '.'
  secretEnv: ['USERNAME', 'PORTAL_USERNAME', 'PORTAL_PASSWORD']

substitutions:
  _ORG: apigeex-mint-kurt
  _ENV: dev
  _SAFILE: cicd-dev.decrypted
  _PROFILE: dev
  _NORTHBOUNDDOMAIN: xapi-dev.kurtkanaskie.net
  _CONFIGOPTIONS: update
  _DEPLOYSUFFIX:
options:
  substitution_option: 'ALLOW_LOOSE'

secrets:
- kmsKeyName: projects/apigeex-mint-kurt/locations/global/keyRings/apigee-cicd-credentials/cryptoKeys/cicd-dev
  secretEnv:
    USERNAME: CiQAPi/lTtResGcwGj1GK+bImae3PBfRAQiKXDl+dRtnR9xMogkSawAZitCxGqsv7fG38qfTiZPFNM5BgeIwkPTV7STSok7pXBU+MeXEphnIK0yafsyUfP1myFv35R1PjLQQE1qt2/0yR5E6mVg3QByPxHu+8jGKAHfqKvb2jstnCuK64Qkp7CbPPJHSJrvV/l/T
    PORTAL_USERNAME: CiQAPi/lTuGJVvQ4lZnz06jt21KZgqJ5C/ab1HY4yv7ZS3UK3LoSNAAZitCxNmlm879zSPwswGKWzNyNZdFM+G5iCN/KklIqjaBABZRDQjfVucxoHEf0b/Xaekg=
    PORTAL_PASSWORD: CiQAPi/lTpT1hAODwpdWWtHUkwIOkg4zw+R55d3xrZX6jUp2PYoSNQAZitCxsONPmco55Zq+1crtdRjlKVxjyYHIlWT4IkmfVSWRoc0F8agDtY/96OXceZTC6cB8

