steps: 
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - "--ciphertext-file=cicd-prod.encrypted"
  - "--plaintext-file=cicd-prod.decrypted"
  - "--location=global"
  - "--keyring=apigee-cicd-credentials"
  - "--key=cicd-prod"
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn -P prod install -Dapigee.username=$$USERNAME -Dapigee.serviceaccount.file=$_SAFILE -Dportal.username=$$PORTAL_USERNAME -Dportal.password=$$PORTAL_PASSWORD -Dcommit="${COMMIT_SHA} via GCP" -Dbranch=${BRANCH_NAME}']
  dir: '.'
  secretEnv: ['USERNAME', 'PORTAL_USERNAME', 'PORTAL_PASSWORD']

substitutions:
  _SAFILE: cicd-prod.decrypted
options:
  substitution_option: 'ALLOW_LOOSE'

secrets:
- kmsKeyName: projects/apigeex-mint-kurt/locations/global/keyRings/apigee-cicd-credentials/cryptoKeys/cicd-prod
  secretEnv:
    USERNAME: CCiQAUgGSU1AnlzGTJxQoHqhuMiHDDxdqRLJjE//Z2jJSqC8O0OMSbABw2zfrbUY4vthHLHpU8WudXHV229V2266E6dJ3X5AkeWwxn7TvKAn1TgkOEPSnLGeh/1JTxUJC5IalPl3IF6/7JfJic9tEVJ7vL2OSm/ySkgga2N2v86rDOM9FuF7rd+t1qGdINHyE+96lFA==
    PORTAL_USERNAME: CiQAUgGSU4SDil7fKTA5UdqgrZ/A3fxzm8vNKL61BHGRAzZhPF0SNABw2zfrkPlDE4yUuZvTVvAm/EiIyv3PudUDdeXCVWN4/T3tSJAnne2+Uc1Y5laexBWEzfo=
    PORTAL_PASSWORD: CiQAUgGSU66IQ/OMe+7nQ8ojONS6Zs9M/Chx0yZljQ/4n2I9geoSNQBw2zfrXlVwTQaXmE8VopiYZBFvl3BhtpaUX/Cg2qJ7/iqtIXYwDP/NZydGNMxZpbYVp0gw
