steps: 
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - "--ciphertext-file=cicd-prod.encrypted"
  - "--plaintext-file=cicd-prod.decrypted"
  - "--location=global"
  - "--keyring=apigee-cicd-credentials"
  - "--key=cicd-prod"
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn -P prod install -Dapigee.username=$$USERNAME -Dapigee.serviceaccount.file=$_SAFILE -Dportal.username=$$PORTAL_USERNAME -Dportal.password=$$PORTAL_PASSWORD -Dcommit="${COMMIT_SHA} via GCP" -Dbranch=${BRANCH_NAME}']
  dir: '.'
  secretEnv: ['USERNAME', 'PORTAL_USERNAME', 'PORTAL_PASSWORD']

substitutions:
  _ORG: apigeex-mint-kurt
  _ENV: prod
  _SAFILE: cicd-prod.decrypted
  _PROFILE: prod
  _NORTHBOUNDDOMAIN: xapi.kurtkanaskie.net
  _CONFIGOPTIONS: update
  _DEPLOYSUFFIX:
options:
  substitution_option: 'ALLOW_LOOSE'

secrets:
- kmsKeyName: projects/apigeex-mint-kurt/locations/global/keyRings/apigee-cicd-credentials/cryptoKeys/cicd-prod
  secretEnv:
    USERNAME: CiQAUgGSUxkgdjjUKiC9qWZvagE+BnBiCHznmDgHFqClCu7wrrkSbABw2zfrJ/gVi2GD9ojk6JlVrcHm0q+j07fMWq8xDhi/l5+s/OPVEsPwlk7qKG6ngSrR6cSCYnKwwtL0DJlduESruFJfYwCNCFKfu62EG75gGE24ZZGugCErz+D0fMaO2Hia9NGxhhNgr5OYXQ==
    PORTAL_USERNAME: CiQAUgGSU8/e55OfNXMoAqbROPC/fgm4hasYff2En5kBtE3IxSESNABw2zfrdx3WeiTVcgNh3zJF+hR/s9nTejMopvx7twmidOF37GAAoaRswYBS3qxdMeHQvR0=
    PORTAL_PASSWORD: CiQAUgGSUx5/Hd1XuQ92I3g+JT5PAMU5knOP2U8/0m4xyMnMK30SNQBw2zfrMBIclcpxS32fMqN/pyPejCs0wBPLUbfZiaeYBfJwWENoJIIiJT6mnJDx2Q7n6DKq
