steps: 
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - "--ciphertext-file=cicd-dev.encrypted"
  - "--plaintext-file=cicd-dev.decrypted"
  - "--location=global"
  - "--keyring=apigee-cicd-credentials"
  - "--key=cicd-dev"
- name: 'gcr.io/cloud-builders/mvn'
  entrypoint: 'bash'
  args: ['-c', 'mvn -P $_PROFILE install -Dapigee.username=$$USERNAME -Dapigee.serviceaccount.file=cicd-dev.decrypted -Dapigee.org=$_ORG -Dapigee.env=$_ENV -Dapi.northbound.domain=$_NORTHBOUNDDOMAIN -Dapigee.config.options=$_CONFIGOPTIONS -Dapigee.config.dir=target/resources/edge -Dapigee.config.exportDir=target/test/integration -Dapi.testtag=@health -Dcommit="${COMMIT_SHA} via GCP" -Dbranch=${BRANCH_NAME}']
  dir: '.'
  secretEnv: ['USERNAME']

substitutions:
  _ORG: apigeex-mint-kurt
  _ENV: dev
  _SAFILE: cicd-dev.decrypted
  _PROFILE: dev
  _NORTHBOUNDDOMAIN: xapi-dev.kurtkanaskie.net
  _CONFIGOPTIONS: update
  _DEPLOYSUFFIX:
options:
  substitution_option: 'ALLOW_LOOSE'

secrets:
- kmsKeyName: projects/apigeex-mint-kurt/locations/global/keyRings/apigee-cicd-credentials/cryptoKeys/cicd-dev
  secretEnv:
    USERNAME: CiQAPi/lTtResGcwGj1GK+bImae3PBfRAQiKXDl+dRtnR9xMogkSawAZitCxGqsv7fG38qfTiZPFNM5BgeIwkPTV7STSok7pXBU+MeXEphnIK0yafsyUfP1myFv35R1PjLQQE1qt2/0yR5E6mVg3QByPxHu+8jGKAHfqKvb2jstnCuK64Qkp7CbPPJHSJrvV/l/T

